# Generated by Django 3.1.5 on 2021-05-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRS', '0002_remove_user_is_applicant'),
    ]

    operations = [
        migrations.CreateModel(
            name='facultyApplicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.TextField()),
                ('firstName', models.TextField()),
                ('middleName', models.TextField()),
                ('emailName', models.EmailField(max_length=254)),
                ('phoneNumber', models.IntegerField()),
            ],
        ),
    ]
