# Generated by Django 3.1.5 on 2021-05-17 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRS', '0003_facultyapplicant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facultyapplicant',
            old_name='emailName',
            new_name='email',
        ),
    ]
