# Generated by Django 3.1.5 on 2021-05-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRS', '0004_auto_20210518_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyapplicant',
            name='firstName',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='facultyapplicant',
            name='lastName',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='facultyapplicant',
            name='middleName',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='facultyapplicant',
            name='phoneNumber',
            field=models.CharField(max_length=150),
        ),
    ]
