# Generated by Django 3.1.5 on 2021-05-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRS', '0005_auto_20210518_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyapplicant',
            name='CV',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
