# Generated by Django 3.1.5 on 2021-05-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRS', '0006_facultyapplicant_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyapplicant',
            name='CV',
            field=models.FileField(null=True, upload_to='facultyApplicant/'),
        ),
    ]
