# Generated by Django 3.1.5 on 2021-05-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRS', '0008_auto_20210521_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyapplicant',
            name='CV',
            field=models.FileField(default=None, null=True, upload_to='facultyApplicant/'),
        ),
        migrations.AlterField(
            model_name='facultyapplicant',
            name='TOR',
            field=models.FileField(default=None, null=True, upload_to='facultyApplicant/'),
        ),
        migrations.AlterField(
            model_name='facultyapplicant',
            name='certificates',
            field=models.FileField(default=None, null=True, upload_to='facultyApplicant/'),
        ),
        migrations.AlterField(
            model_name='facultyapplicant',
            name='credentials',
            field=models.FileField(default=None, null=True, upload_to='facultyApplicant/'),
        ),
    ]
