# Generated by Django 3.1.5 on 2021-05-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRS', '0017_auto_20210521_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyapplicant',
            name='CV',
            field=models.FileField(upload_to='facultyApplicant/'),
        ),
    ]
