# Generated by Django 3.1.5 on 2021-05-25 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRS', '0019_auto_20210521_0342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='CRS.user')),
                ('studentNumber', models.BigIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='facultyapplicant',
            name='CV',
            field=models.FileField(blank=True, null=True, upload_to='facultyApplicant/'),
        ),
    ]
