# Generated by Django 3.1.5 on 2021-05-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRS', '0020_auto_20210525_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentNumber',
            field=models.CharField(max_length=150),
        ),
    ]
